# Configuração para testes simples sem TestContainers
server:
  port: 0

spring:
  application:
    name: store-service-test
  
  # Usar H2 em memória para testes mais rápidos
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: none  # Usar schema.sql ao invés de auto-create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: # Nenhum script de dados inicial

  flyway:
    enabled: false  # Desabilitar Flyway nos testes

  # Desabilitar componentes que precisam de infraestrutura externa
  cache:
    type: simple  # Usar cache simples ao invés do Redis
  
  kafka:
    bootstrap-servers: # Deixar vazio para desabilitar

# Logging
logging:
  level:
    root: INFO
    com.inventory.management: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurações da aplicação
app:
  store-id: STORE_TEST_001
  cache:
    ttl-minutes: 5
  kafka:
    enabled: false
  metrics:
    enabled: true
