spring:
    
  # Database Configuration para Testes
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  # JPA Configuration para Testes
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  # H2 Console para debug
  h2:
    console:
      enabled: true
      
  # Kafka Test Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-central-inventory-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      
# Application Configuration para Testes
app:
  kafka:
    topics:
      inventory-update: test-inventory-update
    consumer:
      group-id: test-central-inventory-group

# Logging Configuration para Testes
logging:
  level:
    com.inventory.management.central: DEBUG
    org.springframework.kafka: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
